apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  myapp-replicaset
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      app: myapp
