apiVersion: v1
kind: Pod
metadata:
  name:  myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: In
              values:
                - front-end
  containers:
    - name: myapp
      image: nginx