#kubectl create secret generic
#kubectl create secret generic \
#    app-secret --from-literal=DB
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
data:
    DB_Host: b64value
    DB_User: b64value
    DB_Password: b64value